export interface AIAsset {
  id: string;
  type: 'texture' | 'character' | 'storyline';
  title: string;
  description: string;
  content: string; // Image URL for textures/characters, text for storyline
  timestamp: string;
}

const textures = [
    {
        title: "Digital Urban Camo",
        description: "Advanced geometric pattern for urban combat environments.",
        content: "/assets/ai/texture.png"
    }
];

const characters = [
    {
        title: "Specter (Recon)",
        description: "Specialized in electronic warfare and long-range surveillance.",
        content: "/assets/ai/recon.png"
    },
    {
        title: "Bulwark (Assault)",
        description: "Front-line heavy infantry with specialized ballistic protection.",
        content: "/assets/ai/assault.png"
    }
];

const stories = [
    "Operation Dark Sky: Infiltrate the Kropotkin facility and retrieve the decrypted telemetry data before the grid collapses.",
    "Siege of Neo-Tokyo: Defend the central data core from a coordinated insurgent strike targeting our global logistics network.",
    "Ghost Signal: Investigate an anomalous frequency originating from the Siberian wastes. Potential deep-cell activation detected."
];

export const aiService = {
  generateTexture: async (): Promise<AIAsset> => {
    await new Promise(r => setTimeout(r, 2000));
    const tex = textures[Math.floor(Math.random() * textures.length)];
    return {
      id: `tex-${Date.now()}`,
      type: 'texture',
      title: tex.title,
      description: tex.description,
      content: tex.content,
      timestamp: new Date().toLocaleTimeString()
    };
  },

  generateCharacter: async (): Promise<AIAsset> => {
    await new Promise(r => setTimeout(r, 2500));
    const char = characters[Math.floor(Math.random() * characters.length)];
    return {
      id: `char-${Date.now()}`,
      type: 'character',
      title: char.title,
      description: char.description,
      content: char.content,
      timestamp: new Date().toLocaleTimeString()
    };
  },

  generateStoryline: async (): Promise<AIAsset> => {
    await new Promise(r => setTimeout(r, 1500));
    const story = stories[Math.floor(Math.random() * stories.length)];
    return {
      id: `story-${Date.now()}`,
      type: 'storyline',
      title: "Mission Briefing",
      description: "Classified tactical narrative generated by AI.",
      content: story,
      timestamp: new Date().toLocaleTimeString()
    };
  }
};
