directories:
  output: release
  buildResources: build
appId: com.kiri.spectredivision
productName: Spectre Division Shadow Reckoning
win:
  target:
    - nsis
    - portable
    - zip
files:
  - filter:
      - dist/**/*
      - electron/**/*
extraMetadata:
  main: electron/main.cjs
electronVersion: 42.2.0
